<?php
	unset($_SESSION['confirmation_message']);
	unset($_SESSION['error_collect']);
	unset($_SESSION['error_object']);
	unset($_SESSION['error_valorization']);
	unset($_SESSION['error_object_weight']);
	unset($_SESSION['error_object_price']);
	unset($_SESSION['error_object_quantity']);
	unset($_SESSION['error_user_name']);
	unset($_SESSION['error_user_password']);
	unset($_SESSION['error_user_privilege']);
	unset($_SESSION['error_site_name']);
	unset($_SESSION['site_menu_value']);
?>